### ISSUE TITLE
Add option to use Paperless Variables (Correspondent, Document Type etc.) in the Subject line or body of the email

### ISSUE THREAD

**Issue by klaasmm** [carlosz1986/paperless-mailservice#13]
It would be great if we had the option to use Paperless Variables in the subject Line or Body of the email, so you can further sort the mail to the right recipients or create follow ups from that.

**Comment by SvenKoeck** [comment]
Additionally it would be great to send documents per mail according to CORRESPONDENT and DOCUMENT TYPE... not to replace TAG-logic, but enhance it!

e. g.:
IF correspondent = "correspondent_1" AND doctype = "type1" SEND TO email_address_1 
IF correspondent = "correspondent_2" AND doctype = "type2" SEND TO email_address_2
IF correspondent = "correspondent_3" SEND TO email_address_3
IF doctype = "type4" SEND TO email_address_4

Individually this would enable more precise processes...

**Comment by carlosz1986** [comment]
> Additionally it would be great to send documents per mail according to CORRESPONDENT and DOCUMENT TYPE... not to replace TAG-logic, but enhance it!
> 
> e. g.: IF correspondent = "correspondent_1" AND doctype = "type1" SEND TO email_address_1 IF correspondent = "correspondent_2" AND doctype = "type2" SEND TO email_address_2 IF correspondent = "correspondent_3" SEND TO email_address_3 IF doctype = "type4" SEND TO email_address_4
> 
> Individually this would enable more precise processes...

I agree, can you create a separate ticket, as this is not connected to this request :-) best

**Comment by carlosz1986** [comment]
@klaasmm testing and feedback are appreciated :-)
you can use the image by using tag 1.6 and in the readme of that branch you find the available variables e.g. placeholders.


`
image: carlosz1986/paperless-mailservice:1.6
`

**Comment by SvenKoeck** [comment]
Hi there,
how is this used? I use Paperless-mobile (by Anton Stubenborn, Android-App) to get docs into my Paperless-ngx-server. After scanning you select correspondent, doc type and Tags and upload scans. After uploading Docs are processed by paperless-mail.
I actually don't see how to use paperless variables. Could you maybe further elaborate how you insist in using this?!
Regards, Sven

**Comment by carlosz1986** [comment]
> WOW! That was a quick addition! Much appreciated (especially as i couldn't get the post consume script solution to run). Unfortunately, test didn't work. :-(
> 
> Failed 1st as document had no owner by default (needs some default / set field to "none" when document has no owner. `error Process Job: could not find user for doc with id=849`
> 
> When set owner for document it failed again with `error Process Job: could not find documentTyppe for doc with id=849`
> 
> Document definitely has a document type - maybe typo? ( find document**Typpe**) or other error?


thx for the nice words, and the testing!
Tbh, I didn't think of having no correspondent, document type or storage path set...I normally use that...

- i changed it to have it optional
- the logging msg you got, was related to missing storage path, but it was wrong. 

You can try it again :-)

**Comment by carlosz1986** [comment]
Glad to hear that :-)

> a.) is it possible to re-read the Config-file on file changes so you don't have to re-start the whole container when updating the config? (will add another issue here) 

Tbh I think restarting the container as a normal approach to do that. Otherwise we should have some Dashboard Interface to set configs on runtime. I wonder if it would be worth the effort to build this... I mean how often do you change this?

> b.) can you also add the "Download URL" to the processed file, so that i not necessarily need so send the attachment?
I was thinking about that as well... We can do that :-)  Will do it before merging... 

best

**Comment by SvenKoeck** [comment]
> > Could you maybe further elaborate in how you're planning to use this?! Thanx in advance! Regards, Sven
> 
> It's just for enhancing the email body or email subject of the emails sent by this server. I want to use this to automatically create tasks in my superlist Account for documents i need to work on (i.e. pay a bill) - and it helps tremendeously when i can get the document type (i.e. "Invoice") or correspondent right from the mail subject, as this determines the subject of my task as well.
> 
> Does this help, @SvenKoeck?

Now I get it! Thanx for your explanation. You're using it very differently to my case. Great, Carlo hast added this for you so fast! Thumbs Up!!! :-)

**Comment by SvenKoeck** [comment]
> Carlo added this really fast and it helps me a great deal! 👍 In fact, I think this should be part of Paperless-ngx itself! 
I agree! The whole paperless-mailservice itself... but I'm glad, Carlo has done this fine pice! ;-)

**Comment by carlosz1986** [comment]
@klaasmm ...
If you like, you can test it again with image version 1.6. I updated the image...

I added the document url variable and some others ... I needed to change for that the base URL of the instance. So please keep in mind to remove the "api" part in the yaml config. 
Besides you can now overwrite the email strings for every rule.

Feedback is welcome :-)
best,

**Comment by carlosz1986** [comment]
> @klaasmm ... If you like, you can test it again with image version 1.6. I updated the image...
> 
> I added the document url variable and some others ... I needed to change for that the base URL of the instance. So please keep in mind to remove the "api" part in the yaml config. Besides you can now overwrite the email strings for every rule.
> 
> Feedback is welcome :-) best,

@klaasmm did you have the chance to test everything once? feedback & help is appreciated, so we can merge it :-) 
i

**Comment by carlosz1986** [comment]
> Hi @carlosz1986 tried it today - worked! Including Document URL. Great stuff! Only one more thing: - is there a way to use HTML Formatting in the Mail Body Statement, so we can make the mail look nicer and make better use of the URL Variable? At least a way to have "<br>" function would be great! Thanks a lot for the great work you do - and i really hope this can become part of Paperless by standard! Best regards, Klaas.

thx :-) We gonna merge this and create a new ticket for html mail ...
cheers.
