### ISSUE TITLE
Addition: Paperless Variables --> mail-subject/-body --> processing FORWARDED emails

### ISSUE THREAD

**Issue by SvenKoeck** [carlosz1986/paperless-mailservice#17]
Hi,
additionally to #13 would it be possible to add reverse functionality: adding tags to an email, that is forwarded to the paperless-ngx-server, where these tags are assigned automatically and furthermore processed accordingly ?
e. g.:
document: "2024-10-07 Correspondent1 Docname1"
1. adding tags to subject or mail body: "2024-10-07 Correspondent1 Docname1 %SendToDatev% %Invoice%"
2. then send e-mail
3. @p-ngx: these two tags "SendToDatev" AND "Invoice" (if found in p-ngx) are assigned after processing and shown in inbox

**Comment by carlosz1986** [comment]
Hi @SvenKoeck ,
I am still trying to understand how this is actually meant. 

You want to add a document to paperless and assign afterwards some tags?

Paperless supports fetching emails via IMAP and then you can define custom workflows to process (+add tags etc.) the document further.

Otherwise please clarify again,
best

**Comment by SvenKoeck** [comment]
Hi @carlosz1986,
I know that PPL-NGX can fetch e-mails and process workflows. Actually it really would be a lot easier to send e-mails with tags/doctypes/correspondents, so (a) either on board it's easier to define workflows or (b) by your addon it would be processed directly...
Perhaps I don't get it or I don't know it better... perhaps I have to read some readmes and come back again!? ;-)

**Comment by carlosz1986** [comment]
I handled that, by using the paperless IMAP fetch function ... 
The nice part is, that it learns automatically based on the document content which tags to apply.
And if I need a special setup, I just setup a second IMAP rule, that basically search for the subject or the content with regular expressions...

I guess most cases will work out of the box...
