### ISSUE TITLE
download file is empty for file without archive path

### ISSUE THREAD

**Issue by jungst** [carlosz1986/paperless-mailservice#18]
Hey 
i got an issue with files that are encrypted.
paperless does not create an archive for such file and uses the original path instead.
This is not detected by the mailservice. Instead it downloads an empty file that is beeing send.

maybe you can add an if clause -> when archive empty try original

attached the logs:
2024/10/08 23:33:10 All processed documents will be marked with Tag: DatevSent at paperless
2024/10/08 23:33:10 found Rule: Datev, that matches Tag(s) (SendToDatev) in document: '' (77)
2024/10/08 23:33:11 downloaded document: '' (77)

would be great thanks.

**Comment by carlosz1986** [comment]
Hi @jungst 
Thx for mentioning this. I have never used encrypted files before. For me the encrypted file is still sent, but the attached filename is wrong and the log message is misleading. 
I fixed it with your proposed work around.

Can you try it by using the testing image tag? 

`image: carlosz1986/paperless-mailservice:testing`

best,
Carlo

**Comment by jungst** [comment]
Hey Carlo,

thanks. All work fine now.
fast fix as always
