### ISSUE TITLE
fix character encoding in email content for utf8 tags

### ISSUE THREAD

**Issue by carlosz1986** [carlosz1986/paperless-mailservice#20]
`test header: kpfÃ¤lligkeit foo bar`

**Comment by tobiasboecker** [comment]
Hi,

having the same problem and trying to fix 
changed line 387 in main.go . but not yet tested
 emailBuf.WriteString(fmt.Sprintf(`Content-Disposition: attachment; filename=UTF-8''"%s"`+"\r\n\r\n", filename))

**Comment by carlosz1986** [comment]
Cool, thx @tobiasboecker for quick reaction ... I won't have time before the weekend and I've just experienced it the first time...
I will check :-)

**Comment by carlosz1986** [comment]
@tobiasboecker would you like to test it? for me body, filename and subject is now encoding properly...

you can use the image:
`image: carlosz1986/paperless-mailservice:1.8`

best,

**Comment by tobiasboecker** [comment]
Hi @carlosz1986 ,

tested for my use case successfully. Filename contains "Test mit öüä#-ß". I started with "docker compose up --build"
