### ISSUE TITLE
Error: Process Job: error getting tags: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by stehol82** [carlosz1986/paperless-mailservice#22]
Unfortunately, I get an error when I start the Docker container on the Synology. 

In the log I find the error message: “error Process Job: error getting tags: invalid character ‘<’ looking for beginning of value” and the container stops. 

Unfortunately, I have no idea what the error is. There is no tag in paperless-ngx that contains '<'

**Comment by carlosz1986** [comment]
I think that occurs when you have entered the API endpoint config value in a wrong format.Which version of the image do you have?One branch ( not merged ) was removing the /API/ part from the URL.Maybe you try a fixed version and not latest? Or the one that is tagged with version 1.3 on GitHub.Am 21.10.2024 22:01 schrieb stehol82 ***@***.***>:
Unfortunately, I get an error when I start the Docker container on the Synology.
In the log I find the error message: “error Process Job: error getting tags: invalid character ‘<’ looking for beginning of value” and the container stops.
Unfortunately, I have no idea what the error is. There is no tag in paperless-ngx that contains '<'

**Comment by stehol82** [comment]
just used /api/ and it worked perfectly. Thanks for that perfect sheet of work
