### ISSUE TITLE
Delete SearchTagName after E-Mail was sent

### ISSUE THREAD

**Issue by stehol82** [carlosz1986/paperless-mailservice#23]
You are currently working with the “SearchTagName” to find the files to be sent. After sending, they also receive the “ProcessedTagName” tag. This means that a sent document has at least three tags at the end. Wouldn't it be better to simply remove the “SearchTagName” once the document has been successfully sent?

**Comment by carlosz1986** [comment]
Hi,
I had a similar discussion already with Sven in another thread. 
My reason for having 2 tags was to have better visibility in paperless what is up for queuing and what is already processed. If you have just one, you won't see both ... And changing this now - even if it would technically work - is some effort...

Btw, why "at least three" ? You mean two? 

best,
Carlo

**Comment by stehol82** [comment]
Ok Carlo, thx for your Feedback. Got IT. All in all a very helpful Script. Thx for your help
