### ISSUE TITLE
Setting for ProcessedTagName before all rules are proceeded

### ISSUE THREAD

**Issue by stehol82** [carlosz1986/paperless-mailservice#24]
Description: When a document meets the criteria of multiple rules (e.g., three different rules for three different recipients), only the first rule is executed. After this initial execution, the ProcessedTagName tag is set, preventing the remaining rules from being processed. As a result, the document is not handled as intended, and the subsequent actions or notifications for the other recipients do not occur.

Steps to Reproduce:

Create three distinct rules that apply to a single document.
Ensure that the document meets the criteria for all three rules.
Submit the document for processing.
Observe that only the first rule is executed and that the ProcessedTagName is set, which halts the processing of the remaining rules.
Expected Behavior: The document should be processed according to all applicable rules, and the ProcessedTagName should only be set after all rules have been evaluated and executed.

Actual Behavior: The ProcessedTagName is set after the first rule is applied, resulting in subsequent rules not being executed.

Impact: This bug affects the workflow of document processing, as it limits the ability to send documents to multiple recipients based on the defined rules. It can lead to missed notifications and incomplete processing of important documents.

Suggested Fix: Adjust the logic for setting the ProcessedTagName so that it only occurs after all applicable rules have been processed. This may involve restructuring the execution flow to ensure that each rule is evaluated before any tags are applied.

**Comment by stehol82** [comment]
Its the Version which was the latest to be used creatin the Container Image on tuesday 22.10. (curently not in office to doublecheck Versionnumber)

Another question, which filename do you use to name the attachment. It seams that, when paperless is changing the filename based on the PAPERLESS_FILENAME_FORMAT variable, the attachment is not name in that naming convention.

BR Stefan

**Comment by carlosz1986** [comment]
Hi Stefan, regarding this issue:
It should be fixed with the latest change in #13. 

As this is merged, could you try the latest docker image or git commit?

`image: carlosz1986/paperless-mailservice:latest`

For the other question I will create another issue, as I need to investigate :-)

best,
Carlo

**Comment by stehol82** [comment]
Perfect works as expected now. Thx.
