### ISSUE TITLE
Problem .env --> is not used --> how to solve?

### ISSUE THREAD

**Issue by SvenKoeck** [carlosz1986/paperless-mailservice#7]
Hi Carlosz1986,
I discovered your tool by chance and was immediately excited about the idea!
I tried to install it but failed with the .env file.
I have created the docker-compose.yml and a paperless-mailservice.env file, but when I use docker-compose up I get the following errors:
```
WARNING: The paperlessInstanceURL variable is not set. Defaulting to a blank string.
WARNING: The paperlessInstanceToken variable is not set. Defaulting to a blank string.
WARNING: The processedTagName variable is not set. Defaulting to a blank string.
WARNING: The searchTagName variable is not set. Defaulting to a blank string.
WARNING: The receiverEmail variable is not set. Defaulting to a blank string.
WARNING: The smtpEmail variable is not set. Defaulting to a blank string.
WARNING: The smtpServer variable is not set. Defaulting to a blank string.
WARNING: The smtpPort variable is not set. Defaulting to a blank string.
WARNING: The smtpUser variable is not set. Defaulting to a blank string.
WARNING: The smtpPassword variable is not set. Defaulting to a blank string.
WARNING: The mailBody variable is not set. Defaulting to a blank string.
WARNING: The mailHeader variable is not set. Defaulting to a blank string.
WARNING: The runEveryXMinute variable is not set. Defaulting to a blank string.
Building paperless-mailservice

```

By renaming the paperless-mailservice.env just to .env I get the following errors:
```Recreating ab8267648cee_paperless-mailservice_paperless-mailservice_1 ... 

ERROR: for ab8267648cee_paperless-mailservice_paperless-mailservice_1  'ContainerConfig'

ERROR: for paperless-mailservice  'ContainerConfig'
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
                ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
             ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 579, in execute_convergence_plan
    return self._execute_convergence_recreate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 499, in _execute_convergence_recreate
    containers, errors = parallel_execute(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
             ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 494, in recreate
    return self.recreate_container(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 612, in recreate_container
    new_container = self.create_container(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 330, in create_container
    container_options = self._get_container_create_options(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 921, in _get_container_create_options
    container_options, override_options = self._build_container_volume_options(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 960, in _build_container_volume_options
    binds, affinity = merge_volume_bindings(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1548, in merge_volume_bindings
    old_volumes, old_mounts = get_container_data_volumes(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1579, in get_container_data_volumes
    container.image_config['ContainerConfig'].get('Volumes') or {}
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'ContainerConfig'
```

Seems I have created them either in the wrong directory or whatever...
I'd appreciate your support, because actually I'm stuck and have no more ideas to solve it!
Best regards
Sven

**Comment by carlosz1986** [comment]
Hi Sven,
Thanks for the kind words! We get this running ;-)
Naming the env file ".env" is definitely right... 

My gut feeling says it's some containing naming conflicts. 

1) Can you post the exact docker-compose.yaml file?
2) Can try to use the modern version "docker compose up" ? This shares maybe more insights.

best,
Carlo

**Comment by SvenKoeck** [comment]
BTW... docker-compose config shows the correct environmental variables!

**Comment by carlosz1986** [comment]
You  actually got it running :-) 

The error "Process Job: error getting tags: failed to fetch tags: 403 Forbidden..." indicates that you have not setup the paperless credentials correctly. Have you entered the token from your paperless instance (user) to the env file? The README explains where you find it at the paperless UI. Maybe you need to grant your users the right permissions on paperless as well ... 

best,
Carlo

**Comment by SvenKoeck** [comment]
Yes, I have. Do I have to activate this user? Or give it a certain role?

**Comment by carlosz1986** [comment]
Tbh I do not have complex role & permission setup for my user as the instance is in my VPN, so this user has most of the permissions granted. But I would assume: Tags, Documents, Document Types are needed for sure... You can try it by adding all and removing step by step ... :-)

**Comment by SvenKoeck** [comment]
seems to be running:
`a72e745357ce_paperless-mailservice-paperless-mailservice-1  | 2024/09/24 21:09:38 no documents found to process`
but actually there is an unprocessed doc, that is tagged with "SendToDatev"...?!

**Comment by SvenKoeck** [comment]
okay... it's an issue with permissions!
I made my user an admin and it worked:
`a72e745357ce_paperless-mailservice-paperless-mailservice-1  | 2024/09/24 21:12:21 downloaded document: 2024-09-22 Sven scan_2024_09_24T18_26_25.pdf`

now it doesn't send the e-mail, so I check the env again:

`a72e745357ce_paperless-mailservice-paperless-mailservice-1  | 2024/09/24 21:12:32 error Process Job: error sending email: unable to send email: EOF
a72e745357ce_paperless-mailservice-paperless-mailservice-1 exited with code 1`

**Comment by SvenKoeck** [comment]
I guess it's the port, TLS@smtp server and server authentification... any idea to activate that within the .env?

**Comment by SvenKoeck** [comment]
`oot@paperless-ngx:/home/paperless-mailservice# docker compose up
[+] Running 1/0
 ✔ Container paperless-mailservice-paperless-mailservice-1  Created                                                    0.0s 
Attaching to paperless-mailservice-1
paperless-mailservice-1  | 2024/09/24 21:23:18 downloaded document: 2024-09-22 Sven scan_2024_09_24T18_26_25.pdf
paperless-mailservice-1  | 2024/09/24 21:23:18 error Process Job: error sending email: unable to send email: 501 Syntax error - line too long
paperless-mailservice-1 exited with code 1`

**Comment by SvenKoeck** [comment]
What's that?

`
2024/09/24 21:23:18 error Process Job: error sending email: unable to send email: 501 Syntax error - line too long
`

**Comment by SvenKoeck** [comment]
paperlessInstanceURL="http://192.168.178.111:8000/api/"
paperlessInstanceToken=123456789012345678901234567890
processedTagName=DatevSent
searchTagName=SendToDatev
receiverEmail=e-mailadress_with_54letters___35lettersBefore@17lettersAfter
smtpEmail=mail@mail.com
smtpServer=smtp.ionos.de
smtpPort=587
smtpUser=username
smtpPassword=password
mailBody="You got a file ..."
mailHeader="You got a file"
runEveryXMinute=1

**Comment by carlosz1986** [comment]
I will try to fix it next weekend :-)

**Comment by carlosz1986** [comment]
Hi Sven,
Some thoughts:
1) The email address length shouldn't be a problem, as I use the same...
2) This error indicates that the mailserver does not accept the character amount for one line (RFC 5321) 
3) It's pretty hard to debug this, as my Mailserver works proper with that setup.

Now I tried to split the binary attachment of the email into multiple lines as well.

Could you try again with a test image, that you get by using `image: carlosz1986/paperless-mailservice:testing` in your docker-compose file?

If that also doesn't help I could try to test it with your mail server provider...

best,
Carlo

**Comment by SvenKoeck** [comment]
Hi,
tried the new docker image:


root@docker:/home/dockeruser/paperless-mailservice# docker compose up
WARN[0000] /home/dockeruser/paperless-mailservice/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 1/1
 ✔ Container 6ba8110045c9_paperless-mailservice_paperless-mailservice_1  Recreated                                     2.8s 
Attaching to paperless-mailservice-1
paperless-mailservice-1  | 2024/09/28 10:19:35 downloaded document: 2024-09-12 Sven BW_730638801.pdf
paperless-mailservice-1  | 2024/09/28 10:19:45 error Process Job: error sending email: unable to send email: EOF
paperless-mailservice-1 exited with code 1

**Comment by jungst** [comment]
Hey also got the EOF Error yesterday. 
On my setup it was the smtp port. I changed to port 587 and it worked fine. 
Email provider Strato. 
This could solve your problem maybe?

**Comment by SvenKoeck** [comment]
I'm using 587... error as before
-------- Ursprüngliche Nachricht --------Von: jungst ***@***.***> Datum: 28.09.24  13:50  (GMT+01:00) An: carlosz1986/paperless-mailservice ***@***.***> Cc: SvenKoeck ***@***.***>, Author ***@***.***> Betreff: Re: [carlosz1986/paperless-mailservice] Problem .env --> is not used --> how to solve? (Issue #7) 
Hey also got the EOF Error yesterday.
On my setup it was the smtp port. I changed to port 587 and it worked fine.
Email provider Strato.
This could solve your problem maybe?

**Comment by carlosz1986** [comment]
I think @jungst is right, this should be connected to some "SSL vs TLS vs STARTTLS" server requirements...

I can't test or fix it for now, as I don't have such a mail server available. @SvenKoeck Could you create me a temporary email account from your provider, so I can figure it out?
If yes, we can connect on linked or x :-)
best,
Carlo

**Comment by SvenKoeck** [comment]
***@***.*** follows via X
-------- Ursprüngliche Nachricht --------Von: carlosz1986 ***@***.***> Datum: 28.09.24  18:08  (GMT+01:00) An: carlosz1986/paperless-mailservice ***@***.***> Cc: SvenKoeck ***@***.***>, Mention ***@***.***> Betreff: Re: [carlosz1986/paperless-mailservice] Problem .env --> is not used --> how to solve? (Issue #7) 
I think @jungst is right, this should be connected to some "SSL vs TLS vs STARTTLS" server requirements...
I can't test or fix it for now, as I don't have such a mail server available. @SvenKoeck Could you create me a temporary email account from your provider, so I can figure it out?
If yes, we can connect on linked or x :-)
best,
Carlo

**Comment by SvenKoeck** [comment]
Please send me your ***@***.***
-------- Ursprüngliche Nachricht --------Von: carlosz1986 ***@***.***> Datum: 28.09.24  18:08  (GMT+01:00) An: carlosz1986/paperless-mailservice ***@***.***> Cc: SvenKoeck ***@***.***>, Mention ***@***.***> Betreff: Re: [carlosz1986/paperless-mailservice] Problem .env --> is not used --> how to solve? (Issue #7) 
I think @jungst is right, this should be connected to some "SSL vs TLS vs STARTTLS" server requirements...
I can't test or fix it for now, as I don't have such a mail server available. @SvenKoeck Could you create me a temporary email account from your provider, so I can figure it out?
If yes, we can connect on linked or x :-)
best,
Carlo

**Comment by SvenKoeck** [comment]
WTF!!!!!!!!!!!!!!
It works... suddenly it works!
I changed the SMTP port from 587 to 465 and then back again to 587 - et voila!
:-D
HAPPY!!!

The original tag "SendToDatev" still remains, although after processing the new one "DatevSent" is now applied in Paperless-NGX. Is this intended? Or should "SendToDatev" be deleted after processing the file?

**Comment by carlosz1986** [comment]
Hi, that is great to hear. So basically last time the port was not set correctly?

I still see your point, that it would be great to support TLS (465) and StartTLS (587) as well.
The demo mail server config you sent me via DM was helpful, so I could simulate it.

Maybe you can help testing it @SvenKoeck ?

https://github.com/carlosz1986/paperless-mailservice/issues/8

Here you find the right Config variables and the README.
I pushed the image to the testing tag in the registry or you can use version 1.3

Feel free to answer in the other ticket, otherwise everything gets more cluttered :-)

best,
Carlo

**Comment by carlosz1986** [comment]
So again, big thanks to @SvenKoeck for testing it... I guess this is solved.
To sum up:
* New version supports TLS and STARTTLS as config, so both smtp ports are working now.
* Both tags will be applied after processing a document
